Add performance Pipeline
nhsd-exeter/dos-integration pull request #102
Opened 2022-01-31 11:25 UTC by JackPlowman

## Link to JIRA Ticket

-

## Description

Please include a summary of the change

### Noteworthy Changes

- These are changes the reviewer should look out for

## Type of change

Delete not appropriate

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## Testing

Please tick the testing that has been completed

- [ ] Unit tests
- [ ] Integration tests

## Developer Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have run the [code formatting checks](../README.md#code-quality)
- [ ] I have run the [code quality checks](../README.md#code-quality)
- [ ] New code meets [standards](https://nhsd-confluence.digital.nhs.uk/display/DI/DI+Ways+of+Working) agreed by the team
- [ ] Unit test code coverage is at or above 80%
- [ ] New and existing unit tests pass locally with my changes
- [ ] Tests have added that prove my fix is effective or that my feature works (Integration tests)
- [ ] I have made corresponding changes to the documentation
- [ ] I have cleaned down my environment (if created)

## Code Reviewer Checklist

- [ ] I have run the unit tests and they run correctly
- [ ] I can confirm the changes have been tested or approved by a tester
- [ ] I can confirm no remaining infrastructure is left over from this branch

2022-02-03 14:29 UTC, ed-sparkes requested changes

2022-02-03 14:29 UTC, ed-sparkes commented on infrastructure/stacks/performance-pipelines/events.tf
> +  schedule_expression = "cron(0 0 ? * 3 *)" # every Tuesday at midnight
can we run this one every day at midnight and the other one every other day at 3am or something so that they dont clash and we get some output daily?

2022-02-04 09:10 UTC, ed-sparkes submitted a review, later dismissed

2022-02-04 09:29 UTC, ed-sparkes approved these changes

2022-02-04 09:33 UTC, rohith1122 approved these changes
LGTM

2022-02-04 09:34 UTC, merged