Task/di 344 pull new tests from nhsuk
nhsd-exeter/dos-integration pull request #177
Opened 2022-03-02 12:38 UTC by Corbisc

## Link to JIRA Ticket

[-](https://nhsd-jira.digital.nhs.uk/browse/DI-344)

## Description

This adds a series of integration tests that NHSUK have that we didn't have coverage for.

### Noteworthy Changes

- None of note

## Type of change

- Integration tests

## Testing

Please tick the testing that has been completed

- [ ] Unit tests
- [ ] Integration tests

## Developer Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have run the [code formatting checks](../README.md#code-quality)
- [ ] I have run the [code quality checks](../README.md#code-quality)
- [ ] New code meets [standards](https://nhsd-confluence.digital.nhs.uk/display/DI/DI+Ways+of+Working) agreed by the team
- [ ] Unit test code coverage is at or above 80%
- [ ] New and existing unit tests pass locally with my changes
- [ ] Tests have added that prove my fix is effective or that my feature works (Integration tests)
- [ ] I have made corresponding changes to the documentation
- [ ] I have cleaned down my environment (if created)

## Code Reviewer Checklist

- [ ] I have run the unit tests and they run correctly
- [ ] I can confirm the changes have been tested or approved by a tester
- [ ] I can confirm no remaining infrastructure is left over from this branch

2022-03-03 09:14 UTC, JackPlowman approved these changes
LGTM 👍

2022-03-03 10:30 UTC, ed-sparkes submitted a review, later dismissed

2022-03-03 15:12 UTC, JackPlowman requested changes
Looks good, couple of minor changes to remove warnings

2022-03-03 15:12 UTC, JackPlowman commented on test/integration/features/F001_Valid_Change_Events.feature
> +@complete @kit
Can the kit tag be removed from this line

2022-03-03 15:12 UTC, JackPlowman commented on test/integration/steps/test_parent_steps.py
> +
In `test/integration/steps/pytest.ini` can you add these lines under the pytest title
```
filterwarnings =
    ignore::DeprecationWarning
```

2022-03-03 15:12 UTC, JackPlowman commented on test/integration/steps/test_parent_steps.py
> +
This comment is unrelated to this file. But the deprecation warning is due to this `DeprecationWarning: invalid escape sequence \/`

2022-03-04 09:26 UTC, JackPlowman commented on test/integration/features/F001_Valid_Change_Events.feature
> +  Scenario: F001S007. A valid change event with special characters is processed by DOS
Can all these tests be marked with `@dev` as well (if they can run on dev/task environments)

2022-03-04 11:33 UTC, ed-sparkes submitted a review, later dismissed

2022-03-04 11:45 UTC, mik3ola submitted a review, later dismissed

2022-03-04 12:17 UTC, JackPlowman approved these changes
LGTM 👍

2022-03-04 12:22 UTC, ed-sparkes approved these changes

2022-03-04 12:22 UTC, merged