DI-212 Mock DoS API Gateway
nhsd-exeter/dos-integration pull request #42
Opened 2021-12-03 10:43 UTC by JackPlowman

## Link to JIRA Ticket

- https://nhsd-jira.digital.nhs.uk/browse/DI-212

## Description

This PR is to add a Mock for the DoS API Gateway. With 2 new lambdas (on using Docker images).

### Noteworthy Changes

- API Gateway to act as DoS API Gateway
- Authoriser Lambda (used by API Gateway)
- DoS API Gateway Lambda (processing for Change Request)
- Updated all terraform to use default tags
- Username and Password for API Gateway is stored in Secrets Manager

## Type of change

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## Testing

Please tick the testing that has been completed

- [x] Unit tests
- [x] Component tests

## Developer Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have run the [code formatting checks](../README.md#code-quality)
- [ ] I have run the [code quality checks](../README.md#code-quality)
- [ ] New code meets [standards](https://nhsd-confluence.digital.nhs.uk/display/DI/DI+Ways+of+Working) agreed by the team
- [ ] Unit test code coverage is at or above 80%
- [ ] New and existing unit tests pass locally with my changes
- [ ] Tests have added that prove my fix is effective or that my feature works (Component tests)
- [ ] I have made corresponding changes to the documentation
- [ ] I have cleaned down my environment (if created)

## Code Reviewer Checklist

- [ ] I have run the unit tests and they run correctly
- [ ] I can confirm the changes have been tested or approved by a tester
- [ ] I can confirm no remaining infrastructure is left over from this branch

2021-12-03 12:01 UTC, ed-sparkes commented
Great work @JackPlowman

2021-12-03 14:33 UTC, JackPlowman commented
Michael and I just test that a change event can be received, run through the process, arrive at the mock, log the change request and pass back a response to the event sender

2021-12-03 15:32 UTC, ed-sparkes requested changes

2021-12-06 07:45 UTC, JackPlowman commented on application/dos_api_gateway/dos_api_gateway.py
> +        change_request_response["dosChanges"].append({"changeId": str(counter) * 9})
This a line  adds a changeId for every change that is received. For example if there is two changes (website and phone) this should return this `{"dosChanges": [{"changeId": "111111111"}, {"changeId": "222222222"}]}`

2021-12-06 09:38 UTC, ed-sparkes approved these changes

2021-12-06 10:03 UTC, rohith1122 approved these changes
1. Run the unit tests and all passed
2. Found a  print statement in dos_api_gateway.py . otherwise looking good

2021-12-06 10:11 UTC, merged

2021-12-06 10:12 UTC, JackPlowman commented
> 1. Run the unit tests and all passed
> 2. Found a  print statement in dos_api_gateway.py . otherwise looking good

At the moment that is the expected behaviour for the demo so that change requests are logged