DI-472 Add change to remove specified dates in the past
nhsd-exeter/dos-integration pull request #434
Opened 2022-07-05 12:27 UTC by mabe13

# Warning

Please don't modify this description yet it will be populated once you create the pull request.

2022-07-06 11:53 UTC, JackPlowman requested changes

2022-07-06 11:53 UTC, JackPlowman commented on application/event_processor/changes.py
> +        logger.debug(
Please can this log level be info

2022-07-06 11:53 UTC, JackPlowman commented on application/event_processor/changes.py
> +        logger.debug(f"Standard weekly opening times not equal. dos={dos_std_open_dates} nhs={nhs_std_open_dates}")
Please can this log level be info

2022-07-06 11:53 UTC, JackPlowman commented on application/event_processor/changes.py
> +    changes = __update_changes_with_sp_opening_times(changes, dos_service, nhs_entity)
Why is one `change = function` and one not?

2022-07-06 11:55 UTC, JackPlowman approved these changes
LGTM 👍

2022-07-06 12:09 UTC, JackPlowman submitted a review, later dismissed
LGTM 👍

2022-07-06 12:44 UTC, JackPlowman approved these changes
LGTM 👍 , ready to merge when tested

2022-07-07 14:51 UTC, Corbisc approved these changes
This is functioning as expected in the 472 environment when tested.

2022-07-07 16:23 UTC, JackPlowman approved these changes

2022-07-07 16:44 UTC, merged