Task/di 266 dos db management handling
nhsd-exeter/dos-integration pull request #66
Opened 2022-01-10 16:08 UTC by SLClayton

## Link to JIRA Ticket

- https://nhsd-jira.digital.nhs.uk/browse/DI-266
- https://nhsd-jira.digital.nhs.uk/browse/DI-268

## Description

These changes ensure protection from SQL-injection attacks from user inputted values and explicitly closes the DoS DB connection at the end of each Lambda execution.

### Noteworthy Changes

- These are changes the reviewer should look out for

## Type of change

Delete not appropriate

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## Testing

Please tick the testing that has been completed

- [ ] Unit tests
- [ ] Component tests

## Developer Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have run the [code formatting checks](../README.md#code-quality)
- [ ] I have run the [code quality checks](../README.md#code-quality)
- [ ] New code meets [standards](https://nhsd-confluence.digital.nhs.uk/display/DI/DI+Ways+of+Working) agreed by the team
- [ ] Unit test code coverage is at or above 80%
- [ ] New and existing unit tests pass locally with my changes
- [ ] Tests have added that prove my fix is effective or that my feature works (Component tests)
- [ ] I have made corresponding changes to the documentation
- [ ] I have cleaned down my environment (if created)

## Code Reviewer Checklist

- [ ] I have run the unit tests and they run correctly
- [ ] I can confirm the changes have been tested or approved by a tester
- [ ] I can confirm no remaining infrastructure is left over from this branch

2022-01-10 16:12 UTC, ed-sparkes commented on application/event_processor/event_processor.py
> +    disconnect_dos_db()
this need to be in a finally block so that it is still attempeted in event of intermediate code throwing an exception

2022-01-11 10:50 UTC, ed-sparkes approved these changes

2022-01-13 08:24 UTC, JackPlowman requested changes
Couple of small changes request, but overall looks good.

2022-01-13 08:24 UTC, JackPlowman commented on application/event_processor/dos.py
> +            logger.error(f"There was an exception while trying to close DoS database connection: {e}")
Can this be logger.exception as it shows both a logger.error and prints the stack trace

2022-01-13 08:24 UTC, JackPlowman commented on application/event_processor/tests/test_dos.py
> +def test_disconnect_dos_db():
Can this test function assert that a connection is closed. Maybe use magicmock as the db connection and assert the close method is called.

2022-01-13 10:27 UTC, ed-sparkes approved these changes

2022-01-13 13:13 UTC, ed-sparkes submitted a review, later dismissed

2022-01-13 14:09 UTC, JackPlowman approved these changes
LGTM 👍

2022-01-13 15:58 UTC, ed-sparkes approved these changes

2022-01-13 16:51 UTC, mabe13 submitted a review, later dismissed
LGTM 👍

2022-01-13 17:02 UTC, mabe13 approved these changes

2022-01-13 17:02 UTC, merged