Merged up from 240
nhsd-exeter/dos-integration pull request #77
Opened 2022-01-18 08:04 UTC by ed-sparkes

## Link to JIRA Ticket

-

## Description

Please include a summary of the change

### Noteworthy Changes

- These are changes the reviewer should look out for

## Type of change

Delete not appropriate

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## Testing

Please tick the testing that has been completed

- [ ] Unit tests
- [ ] Component tests

## Developer Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have run the [code formatting checks](../README.md#code-quality)
- [ ] I have run the [code quality checks](../README.md#code-quality)
- [ ] New code meets [standards](https://nhsd-confluence.digital.nhs.uk/display/DI/DI+Ways+of+Working) agreed by the team
- [ ] Unit test code coverage is at or above 80%
- [ ] New and existing unit tests pass locally with my changes
- [ ] Tests have added that prove my fix is effective or that my feature works (Component tests)
- [ ] I have made corresponding changes to the documentation
- [ ] I have cleaned down my environment (if created)

## Code Reviewer Checklist

- [ ] I have run the unit tests and they run correctly
- [ ] I can confirm the changes have been tested or approved by a tester
- [ ] I can confirm no remaining infrastructure is left over from this branch

2022-01-18 11:54 UTC, JackPlowman requested changes

2022-01-18 11:54 UTC, JackPlowman commented on application/event_sender/event_sender.py
> +    now_ms = time_ns() // 1000000
Is this milliseconds or nanoseconds? As we are using milliseconds elsewhere is this a problem for the latency calculation.
https://www.geeksforgeeks.org/python-time-time_ns-method/

2022-01-18 12:20 UTC, JackPlowman submitted a review, later dismissed
LGTM 👍

2022-01-19 13:28 UTC, rohith1122 submitted a review, later dismissed
LGTM.

2022-01-20 08:27 UTC, JackPlowman approved these changes
LGTM 👍

2022-01-20 08:34 UTC, rohith1122 approved these changes

2022-01-20 08:58 UTC, merged